### PR TITLE
fix(packaging): include *.yml files from tests

### LINKED ISSUE #40: `tests/parsers/ebml` missing from sdist for 0.5.0
The sdist archive for 0.5.0 is missing the `tests/parsers/ebml` directory, which leads to test failures:

```pytb
____________________________________________________ EBMLTestCase.test_parse_full _____________________________________________________

self = <test_parsers.EBMLTestCase testMethod=test_parse_full>

    def setUp(self):
        self.stream = io.open(os.path.join(TEST_DIR, "test1.mkv"), "rb")
>       with io.open(os.path.join(EBML_VALIDATION_DIR, "test1.mkv.yml"), "r") as yml:
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/portage/dev-python/enzyme-0.5.0/work/enzyme-0.5.0/tests/parsers/e
bml/test1.mkv.yml'

self       = <test_parsers.EBMLTestCase testMethod=test_parse_full>

tests/test_parsers.py:27: FileNotFoundError
```

(and so on)

### PR DESCRIPTION
**Pull request by mgorny**
Fixes #40

### CODE REVIEW

**Comment by Diaoul** [comment]
Thanks, do you know if there is a way to avoid using MANIFEST.in just for that and use some pyproject options?

**Comment by mgorny** [comment]
I've digged through setuptools documentation, asked a knowledgeable person — and apparently not, there's no replacement for `MANIFEST.in` at this point.

I suppose you could use `setuptools-scm`, and then *I think* everything from the git repository would end up in sdist — but not sure if that's what you want.

**Comment by Diaoul** [comment]
I went deep yesterday in how setuptools work and from what I understand, options to include or exclude are mostly related to the package itself (i.e. enzyme) and not tests.

I think this current PR needs tweaking though, I'm afraid it risks including tests/data which is populated with some XML when running tests. Will take a look this evening (CEST).

**Comment by mgorny** [comment]
I can change it to list that one file, if you prefer. I've assumed no other `.yml` files should end up there.

**Comment by Diaoul** [comment]
Nevermind, it's actually .xml files that we download as test data :+1:

**Comment by Diaoul** [comment]
```fish
❯ rm -fr dist/ build/ enzyme.egg-info/ enzyme-0.5.2 && python -m build -s && tar -xzvf dist/enzyme-0.5.2.tar.gz && eza -laT enzyme-0.5.2
```

image

**Comment by mgorny** [comment]
Thanks!

**Pull request merged**
